### ISSUE TITLE
How connection string have to be given

### ISSUE THREAD

**Issue by athul-p** [lokeshlal/TextToSql#3]

**Comment by lokeshlal** [comment]
In `configuration/config.json` file, set `connection_string` field. 

"connection_string":"Driver={ODBC Driver 13 for SQL Server};Server=`{SERVER}`;Database=`{DATABASE}`;Uid=`{USERID}`;Pwd=`{PASSWORD}`;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

The above is standard SQL server connection string.

**Comment by athul-p** [comment]
thank you
